//
// Created by msullivan on 5/18/24.
//

#pragma once
#include <string>
#include <ncurses.h>

namespace CursesGUI
{
    enum MouseInput
    {
        // Left mouse button
        LEFT_PRESS                          = BUTTON1_PRESSED,
        LEFT_CLICK                          = BUTTON1_CLICKED,
        LEFT_DOUBLE_CLICK                   = BUTTON1_DOUBLE_CLICKED,
        LEFT_TRIPLE_CLICK                   = BUTTON1_TRIPLE_CLICKED,
        LEFT_RELEASE                        = BUTTON1_RELEASED,

        SHIFT_LEFT_PRESS                    = BUTTON_SHIFT & BUTTON1_PRESSED,
        SHIFT_LEFT_CLICK                    = BUTTON_SHIFT & BUTTON1_CLICKED,
        SHIFT_LEFT_DOUBLE_CLICK             = BUTTON_SHIFT & BUTTON1_DOUBLE_CLICKED,
        SHIFT_LEFT_TRIPLE_CLICK             = BUTTON_SHIFT & BUTTON1_TRIPLE_CLICKED,
        SHIFT_LEFT_RELEASE                  = BUTTON_SHIFT & BUTTON1_RELEASED,

        CTRL_LEFT_PRESS                     = BUTTON_CTRL & BUTTON1_PRESSED,
        CTRL_LEFT_CLICK                     = BUTTON_CTRL & BUTTON1_CLICKED,
        CTRL_LEFT_DOUBLE_CLICK              = BUTTON_CTRL & BUTTON1_DOUBLE_CLICKED,
        CTRL_LEFT_TRIPLE_CLICK              = BUTTON_CTRL & BUTTON1_TRIPLE_CLICKED,
        CTRL_LEFT_RELEASE                   = BUTTON_CTRL & BUTTON1_RELEASED,

        ALT_LEFT_PRESS                      = BUTTON_ALT & BUTTON1_PRESSED,
        ALT_LEFT_CLICK                      = BUTTON_ALT & BUTTON1_CLICKED,
        ALT_LEFT_DOUBLE_CLICK               = BUTTON_ALT & BUTTON1_DOUBLE_CLICKED,
        ALT_LEFT_TRIPLE_CLICK               = BUTTON_ALT & BUTTON1_TRIPLE_CLICKED,
        ALT_LEFT_RELEASE                    = BUTTON_ALT & BUTTON1_RELEASED,

        CTRL_SHIFT_LEFT_PRESS               = BUTTON_CTRL & BUTTON_SHIFT & BUTTON1_PRESSED,
        CTRL_SHIFT_LEFT_CLICK               = BUTTON_CTRL & BUTTON_SHIFT & BUTTON1_CLICKED,
        CTRL_SHIFT_LEFT_DOUBLE_CLICK        = BUTTON_CTRL & BUTTON_SHIFT & BUTTON1_DOUBLE_CLICKED,
        CTRL_SHIFT_LEFT_TRIPLE_CLICK        = BUTTON_CTRL & BUTTON_SHIFT & BUTTON1_TRIPLE_CLICKED,
        CTRL_SHIFT_LEFT_RELEASE             = BUTTON_CTRL & BUTTON_SHIFT & BUTTON1_RELEASED,

        ALT_SHIFT_LEFT_PRESS                = BUTTON_ALT & BUTTON_SHIFT & BUTTON1_PRESSED,
        ALT_SHIFT_LEFT_CLICK                = BUTTON_ALT & BUTTON_SHIFT & BUTTON1_CLICKED,
        ALT_SHIFT_LEFT_DOUBLE_CLICK         = BUTTON_ALT & BUTTON_SHIFT & BUTTON1_DOUBLE_CLICKED,
        ALT_SHIFT_LEFT_TRIPLE_CLICK         = BUTTON_ALT & BUTTON_SHIFT & BUTTON1_TRIPLE_CLICKED,
        ALT_SHIFT_LEFT_RELEASE              = BUTTON_ALT & BUTTON_SHIFT & BUTTON1_RELEASED,

        CTRL_ALT_LEFT_PRESS                 = BUTTON_CTRL & BUTTON_ALT & BUTTON1_PRESSED,
        CTRL_ALT_LEFT_CLICK                 = BUTTON_CTRL & BUTTON_ALT & BUTTON1_CLICKED,
        CTRL_ALT_LEFT_DOUBLE_CLICK          = BUTTON_CTRL & BUTTON_ALT & BUTTON1_DOUBLE_CLICKED,
        CTRL_ALT_LEFT_TRIPLE_CLICK          = BUTTON_CTRL & BUTTON_ALT & BUTTON1_TRIPLE_CLICKED,
        CTRL_ALT_LEFT_RELEASE               = BUTTON_CTRL & BUTTON_ALT & BUTTON1_RELEASED,

        CTRL_ALT_SHIFT_LEFT_PRESS           = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON1_PRESSED,
        CTRL_ALT_SHIFT_LEFT_CLICK           = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON1_CLICKED,
        CTRL_ALT_SHIFT_LEFT_DOUBLE_CLICK    = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON1_DOUBLE_CLICKED,
        CTRL_ALT_SHIFT_LEFT_TRIPLE_CLICK    = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON1_TRIPLE_CLICKED,
        CTRL_ALT_SHIFT_LEFT_RELEASE         = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON1_RELEASED,

        // Mouse wheel
        WHEEL_PRESS                         = BUTTON2_PRESSED,
        WHEEL_CLICK                         = BUTTON2_CLICKED,
        WHEEL_DOUBLE_CLICK                  = BUTTON2_DOUBLE_CLICKED,
        WHEEL_TRIPLE_CLICK                  = BUTTON2_TRIPLE_CLICKED,
        WHEEL_RELEASE                       = BUTTON2_RELEASED,

        SHIFT_WHEEL_PRESS                   = BUTTON_SHIFT & BUTTON2_PRESSED,
        SHIFT_WHEEL_CLICK                   = BUTTON_SHIFT & BUTTON2_CLICKED,
        SHIFT_WHEEL_DOUBLE_CLICK            = BUTTON_SHIFT & BUTTON2_DOUBLE_CLICKED,
        SHIFT_WHEEL_TRIPLE_CLICK            = BUTTON_SHIFT & BUTTON2_TRIPLE_CLICKED,
        SHIFT_WHEEL_RELEASE                 = BUTTON_SHIFT & BUTTON2_RELEASED,

        CTRL_WHEEL_PRESS                    = BUTTON_CTRL & BUTTON2_PRESSED,
        CTRL_WHEEL_CLICK                    = BUTTON_CTRL & BUTTON2_CLICKED,
        CTRL_WHEEL_DOUBLE_CLICK             = BUTTON_CTRL & BUTTON2_DOUBLE_CLICKED,
        CTRL_WHEEL_TRIPLE_CLICK             = BUTTON_CTRL & BUTTON2_TRIPLE_CLICKED,
        CTRL_WHEEL_RELEASE                  = BUTTON_CTRL & BUTTON2_RELEASED,

        ALT_WHEEL_PRESS                     = BUTTON_ALT & BUTTON2_PRESSED,
        ALT_WHEEL_CLICK                     = BUTTON_ALT & BUTTON2_CLICKED,
        ALT_WHEEL_DOUBLE_CLICK              = BUTTON_ALT & BUTTON2_DOUBLE_CLICKED,
        ALT_WHEEL_TRIPLE_CLICK              = BUTTON_ALT & BUTTON2_TRIPLE_CLICKED,
        ALT_WHEEL_RELEASE                   = BUTTON_ALT & BUTTON2_RELEASED,

        CTRL_SHIFT_WHEEL_PRESS              = BUTTON_CTRL & BUTTON_SHIFT & BUTTON2_PRESSED,
        CTRL_SHIFT_WHEEL_CLICK              = BUTTON_CTRL & BUTTON_SHIFT & BUTTON2_CLICKED,
        CTRL_SHIFT_WHEEL_DOUBLE_CLICK       = BUTTON_CTRL & BUTTON_SHIFT & BUTTON2_DOUBLE_CLICKED,
        CTRL_SHIFT_WHEEL_TRIPLE_CLICK       = BUTTON_CTRL & BUTTON_SHIFT & BUTTON2_TRIPLE_CLICKED,
        CTRL_SHIFT_WHEEL_RELEASE            = BUTTON_CTRL & BUTTON_SHIFT & BUTTON2_RELEASED,

        ALT_SHIFT_WHEEL_PRESS               = BUTTON_ALT & BUTTON_SHIFT & BUTTON2_PRESSED,
        ALT_SHIFT_WHEEL_CLICK               = BUTTON_ALT & BUTTON_SHIFT & BUTTON2_CLICKED,
        ALT_SHIFT_WHEEL_DOUBLE_CLICK        = BUTTON_ALT & BUTTON_SHIFT & BUTTON2_DOUBLE_CLICKED,
        ALT_SHIFT_WHEEL_TRIPLE_CLICK        = BUTTON_ALT & BUTTON_SHIFT & BUTTON2_TRIPLE_CLICKED,
        ALT_SHIFT_WHEEL_RELEASE             = BUTTON_ALT & BUTTON_SHIFT & BUTTON2_RELEASED,

        CTRL_ALT_WHEEL_PRESS                = BUTTON_CTRL & BUTTON_ALT & BUTTON2_PRESSED,
        CTRL_ALT_WHEEL_CLICK                = BUTTON_CTRL & BUTTON_ALT & BUTTON2_CLICKED,
        CTRL_ALT_WHEEL_DOUBLE_CLICK         = BUTTON_CTRL & BUTTON_ALT & BUTTON2_DOUBLE_CLICKED,
        CTRL_ALT_WHEEL_TRIPLE_CLICK         = BUTTON_CTRL & BUTTON_ALT & BUTTON2_TRIPLE_CLICKED,
        CTRL_ALT_WHEEL_RELEASE              = BUTTON_CTRL & BUTTON_ALT & BUTTON2_RELEASED,

        CTRL_ALT_SHIFT_WHEEL_PRESS          = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON2_PRESSED,
        CTRL_ALT_SHIFT_WHEEL_CLICK          = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON2_CLICKED,
        CTRL_ALT_SHIFT_WHEEL_DOUBLE_CLICK   = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON2_DOUBLE_CLICKED,
        CTRL_ALT_SHIFT_WHEEL_TRIPLE_CLICK   = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON2_TRIPLE_CLICKED,
        CTRL_ALT_SHIFT_WHEEL_RELEASE        = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON2_RELEASED,

        // Right mouse button
        RIGHT_PRESS                         = BUTTON3_PRESSED,
        RIGHT_CLICK                         = BUTTON3_CLICKED,
        RIGHT_DOUBLE_CLICK                  = BUTTON3_DOUBLE_CLICKED,
        RIGHT_TRIPLE_CLICK                  = BUTTON3_TRIPLE_CLICKED,
        RIGHT_RELEASE                       = BUTTON3_RELEASED,

        SHIFT_RIGHT_PRESS                   = BUTTON_SHIFT & BUTTON3_PRESSED,
        SHIFT_RIGHT_CLICK                   = BUTTON_SHIFT & BUTTON3_CLICKED,
        SHIFT_RIGHT_DOUBLE_CLICK            = BUTTON_SHIFT & BUTTON3_DOUBLE_CLICKED,
        SHIFT_RIGHT_TRIPLE_CLICK            = BUTTON_SHIFT & BUTTON3_TRIPLE_CLICKED,
        SHIFT_RIGHT_RELEASE                 = BUTTON_SHIFT & BUTTON3_RELEASED,

        CTRL_RIGHT_PRESS                    = BUTTON_CTRL & BUTTON3_PRESSED,
        CTRL_RIGHT_CLICK                    = BUTTON_CTRL & BUTTON3_CLICKED,
        CTRL_RIGHT_DOUBLE_CLICK             = BUTTON_CTRL & BUTTON3_DOUBLE_CLICKED,
        CTRL_RIGHT_TRIPLE_CLICK             = BUTTON_CTRL & BUTTON3_TRIPLE_CLICKED,
        CTRL_RIGHT_RELEASE                  = BUTTON_CTRL & BUTTON3_RELEASED,

        ALT_RIGHT_PRESS                     = BUTTON_ALT & BUTTON3_PRESSED,
        ALT_RIGHT_CLICK                     = BUTTON_ALT & BUTTON3_CLICKED,
        ALT_RIGHT_DOUBLE_CLICK              = BUTTON_ALT & BUTTON3_DOUBLE_CLICKED,
        ALT_RIGHT_TRIPLE_CLICK              = BUTTON_ALT & BUTTON3_TRIPLE_CLICKED,
        ALT_RIGHT_RELEASE                   = BUTTON_ALT & BUTTON3_RELEASED,

        CTRL_SHIFT_RIGHT_PRESS              = BUTTON_CTRL & BUTTON_SHIFT & BUTTON3_PRESSED,
        CTRL_SHIFT_RIGHT_CLICK              = BUTTON_CTRL & BUTTON_SHIFT & BUTTON3_CLICKED,
        CTRL_SHIFT_RIGHT_DOUBLE_CLICK       = BUTTON_CTRL & BUTTON_SHIFT & BUTTON3_DOUBLE_CLICKED,
        CTRL_SHIFT_RIGHT_TRIPLE_CLICK       = BUTTON_CTRL & BUTTON_SHIFT & BUTTON3_TRIPLE_CLICKED,
        CTRL_SHIFT_RIGHT_RELEASE            = BUTTON_CTRL & BUTTON_SHIFT & BUTTON3_RELEASED,

        ALT_SHIFT_RIGHT_PRESS               = BUTTON_ALT & BUTTON_SHIFT & BUTTON3_PRESSED,
        ALT_SHIFT_RIGHT_CLICK               = BUTTON_ALT & BUTTON_SHIFT & BUTTON3_CLICKED,
        ALT_SHIFT_RIGHT_DOUBLE_CLICK        = BUTTON_ALT & BUTTON_SHIFT & BUTTON3_DOUBLE_CLICKED,
        ALT_SHIFT_RIGHT_TRIPLE_CLICK        = BUTTON_ALT & BUTTON_SHIFT & BUTTON3_TRIPLE_CLICKED,
        ALT_SHIFT_RIGHT_RELEASE             = BUTTON_ALT & BUTTON_SHIFT & BUTTON3_RELEASED,

        CTRL_ALT_RIGHT_PRESS                = BUTTON_CTRL & BUTTON_ALT & BUTTON3_PRESSED,
        CTRL_ALT_RIGHT_CLICK                = BUTTON_CTRL & BUTTON_ALT & BUTTON3_CLICKED,
        CTRL_ALT_RIGHT_DOUBLE_CLICK         = BUTTON_CTRL & BUTTON_ALT & BUTTON3_DOUBLE_CLICKED,
        CTRL_ALT_RIGHT_TRIPLE_CLICK         = BUTTON_CTRL & BUTTON_ALT & BUTTON3_TRIPLE_CLICKED,
        CTRL_ALT_RIGHT_RELEASE              = BUTTON_CTRL & BUTTON_ALT & BUTTON3_RELEASED,

        CTRL_ALT_SHIFT_RIGHT_PRESS          = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON3_PRESSED,
        CTRL_ALT_SHIFT_RIGHT_CLICK          = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON3_CLICKED,
        CTRL_ALT_SHIFT_RIGHT_DOUBLE_CLICK   = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON3_DOUBLE_CLICKED,
        CTRL_ALT_SHIFT_RIGHT_TRIPLE_CLICK   = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON3_TRIPLE_CLICKED,
        CTRL_ALT_SHIFT_RIGHT_RELEASE        = BUTTON_CTRL & BUTTON_ALT & BUTTON_SHIFT & BUTTON3_RELEASED,
    };

    enum class InputMode
    {
        SELECT,
        MOVE,
        TYPE,
        RESIZE
    };

    using Key = std::string;
    using Mouse = unsigned int;
    struct Input
    {
        Key key;
        Mouse mouse = 0;
        int mouseY = -1, mouseX = -1;
    };

    using Binds = std::unordered_set<Input, std::function<void()>>;

    inline Input getInput()
    {
        Input input;
        MEVENT mouseEvent;

        input.key = keyname(getch());
        input.mouse = mouseEvent.bstate;
        input.mouseY = mouseEvent.y;
        input.mouseX = mouseEvent.x;

        return input;
    }

    void processInput();
}